[package]
name = "rinzler"
version = "0.1.0-alpha"
edition = "2024"
description = "Rinzler - a somewhat intelligent API scanner"
authors = ["akses0 <akses0@pm.me>"]
license = "AGPL-3"
repository = "https://github.com/akses0/rinzler"

[dependencies]

# Just reference workspace deps (no versions needed!)
clap.workspace = true
clap-cargo = "0.18.3"
url = "2.5.7"