[package]
name = "rinzler"
version.workspace = true
edition.workspace = true
description.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]

# Just reference workspace deps (no versions needed!)
clap.workspace = true
clap-cargo = "0.18.3"
url = "2.5.7"